/// Flutter icons AddImage
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AddImage
///      fonts:
///       - asset: fonts/AddImage.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AddImage {
  AddImage._();

  static const _kFontFam = 'AddImage';
  static const String? _kFontPkg = null;

  static const IconData add_image = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
