/// Flutter icons Calendar
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Calendar
///      fonts:
///       - asset: fonts/Calendar.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Calendar {
  Calendar._();

  static const _kFontFam = 'Calendar';
  static const String? _kFontPkg = null;

  static const IconData event = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
