/// Flutter icons ClipBoardCheck
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ClipBoardCheck
///      fonts:
///       - asset: fonts/ClipBoardCheck.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ClipBoardCheck {
  ClipBoardCheck._();

  static const _kFontFam = 'ClipBoardCheck';
  static const String? _kFontPkg = null;

  static const IconData clipboard_check = IconData(0xf46c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
