/// Flutter icons Outlet
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Outlet
///      fonts:
///       - asset: fonts/Outlet.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Outlet {
  Outlet._();

  static const _kFontFam = 'Outlet';
  static const String? _kFontPkg = null;

  static const IconData industrial_building = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
